### PR TITLE
Timeout

### PR DESCRIPTION
**Pull request by sven-ruess**
Added a connection timeout.

### CODE REVIEW

**Comment by CLiX-1** [comment]
@sven-ruess Thanks for your ideas!
I've been thinking about this and I'm not sure if the timeout option will solve any problem. 
Is there a specific reason for the timeout?
As far as I know, there is no default timeout for Python "requests". So all API requests will run until the checkmk timeout is reached or the api server sends a timeout. If you want to have a longer client timeout, I think you can control this with the rules "Service check timeout (micro core)" and "Normal check interval for service checks".
Actually, if we define a custom timeout, then the script may stop earlier than the checkmk timeout. But I do not see any benefit.
Please correct me if I‘m wrong.

**Comment by sven-ruess** [comment]
Hi @CLiX-1,

yes, there is a general timeout implemented in Checkmk. This value is used for active checks and can be configured in _General -> Check plugin timeout_. Default value is 1 minute.

The rule _Service check timeout (micro core)_ can be used to configure timeout service related.

Python packages requests uses a standard timeout of 60 seconds.

Rule _Normal check interval for service checks_ configures the interval for doing an execution of this check. It is not related to timeout.

With a custom timeout for queries you can take care about the usage of the checkers. Every active check is assigned to a checker, which will query the data. If you have long timeouts, the checker is blocked for others. So yes it makes sense to configure a short timeout, where the queries normally finish successfully.

I hope you can understand the relations between all the things.

I implemented those options, because a customer needs it. He must configure a proxy for the query and with the timeout we take care about the time, which will block a checker.

The result is, that we do not block it longer as needed. Checkers should query the data and return. Normally 5 seconds is enough. Then this checker should query further information for other host or checks.

Best regards

**Comment by CLiX-1** [comment]
@sven-ruess What I meant was that you need to adjust the "Normal check interval for service checks" rule if this check takes longer than 1 minute in your environment.
But I understand that you do not want to block resources if a query takes longer than the defined timeout.

If one query takes a little bit longer than the defined timeout, but all the others are running fast, then you will get an error for the whole special agent. 
That's why I'm a little cautious about this option. I do not want this implementation to cause more problems than it solves.
If you want to lower the timeout for the special agent, you can do so with the "Service check timeout (micro core)" rule.

**Comment by sven-ruess** [comment]
Yes that is correct. We are using this check in a very big environment. All our HTTP checks have a timeout implemented. In normal conditions all is working as expected.
If the timeout is raised it is okay for us, that the agent fails and shows the error. Then we can take care about it.

All modern HTTP checks have a timeout implemented. That is a general way from Checkmk. So I think, we should do it here, too. Our server is between 80% and 90% of load. That is a great value. Without the timeout, the system get out of order, because the checkers a blocked to long and do nothing. With this option, we take care about that in failure situations the system will do its job.

At the moment I am doing a rework to restructure the code. That will help for further changes and make it easier to adapt. MR will follow after I have finished the work

**Comment by sven-ruess** [comment]
Okay. I have tested again in customer environment. If firewall blocks communication then without any timeout discovery is running forever. System is slowly getting overloaded.

With timeout discovery is canceled and an error is shown. That is great, because customer can take care about it.

**Pull request merged**
